# Multi Layer Perceptron (MLP)

In [1]:
import numpy as np
import tensorflow as tf
from sklearn.datasets import fetch_covtype
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import roc_auc_score, average_precision_score, log_loss
from sklearn.metrics import cohen_kappa_score, confusion_matrix, brier_score_loss
from sklearn.metrics import matthews_corrcoef, fowlkes_mallows_score, r2_score
from sklearn.metrics import precision_recall_curve, roc_curve, top_k_accuracy_score

# Load the forest cover type dataset
data = fetch_covtype()
X, y = data.data, data.target

# Adjust labels to be in the range 0 to 6
y = y - 1

# Standardize the dataset
scaler = StandardScaler()
X = scaler.fit_transform(X)

# One-hot encode the target variable
encoder = OneHotEncoder(sparse=False)
y_onehot = encoder.fit_transform(y.reshape(-1, 1))

# Split the data into train and test sets
X_train, X_test, y_train, y_test, y_train_onehot, y_test_onehot = train_test_split(X, y, y_onehot, test_size=0.2, random_state=42)

# Build the MLP model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(y_onehot.shape[1], activation='softmax')
])

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train_onehot, epochs=20, batch_size=32, verbose=1, validation_split=0.2)

# Make predictions on the test set
y_prob = model.predict(X_test)
y_pred = np.argmax(y_prob, axis=1)

# Calculate evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='macro')
recall = recall_score(y_test, y_pred, average='macro')
f1 = f1_score(y_test, y_pred, average='macro')
roc_auc = roc_auc_score(y_test_onehot, y_prob, multi_class='ovr')
pr_auc = average_precision_score(y_test_onehot, y_prob, average='macro')
log_loss_value = log_loss(y_test_onehot, y_prob)
kappa = cohen_kappa_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

# Calculate Brier score for each class and average it
num_classes = y_onehot.shape[1]
brier_scores = [brier_score_loss(y_test_onehot[:, i], y_prob[:, i]) for i in range(num_classes)]
brier_score_avg = np.mean(brier_scores)

mcc = matthews_corrcoef(y_test, y_pred)
fmi = fowlkes_mallows_score(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

# Calculate precision-recall curve and ROC curve for each class
precision_dict, recall_dict, fpr_dict, tpr_dict = {}, {}, {}, {}
for i in range(num_classes):
    precision_dict[i], recall_dict[i], _ = precision_recall_curve(y_test_onehot[:, i], y_prob[:, i])
    fpr_dict[i], tpr_dict[i], _ = roc_curve(y_test_onehot[:, i], y_prob[:, i])
    auc = roc_auc_score(y_test_onehot[:, i], y_prob[:, i])
    print(f"AUC-ROC for Class {i}: {auc:.3f}")

# Calculate top-k accuracy
top_k_acc = top_k_accuracy_score(y_test, y_prob, k=3)

print(f"Accuracy: {accuracy:.3f}")
print(f"Precision: {precision:.3f}")
print(f"Recall: {recall:.3f}")
print(f"F1-Score: {f1:.3f}")
print(f"AUC-ROC: {roc_auc:.3f}")
print(f"AUC-PR: {pr_auc:.3f}")
print(f"Log Loss: {log_loss_value:.3f}")
print(f"Cohen's Kappa: {kappa:.3f}")
print(f"Confusion Matrix:\n{conf_matrix}")
print(f"Average Brier Score: {brier_score_avg:.3f}")
print(f"Matthews Correlation Coefficient: {mcc:.3f}")
print(f"Fowlkes-Mallows Index: {fmi:.3f}")
print(f"Coefficient of Determination (R^2): {r2:.3f}")
print(f"Top-3 Accuracy: {top_k_acc:.3f}")

C:\Users\Madhu Mohan Vamsi\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
C:\Users\Madhu Mohan Vamsi\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/20
11621/11621 ━━━━━━━━━━━━━━━━━━━━ 72s 6ms/step - accuracy: 0.7479 - loss: 0.6004 - val_accuracy: 0.8170 - val_loss: 0.4340
Epoch 2/20
11621/11621 ━━━━━━━━━━━━━━━━━━━━ 67s 6ms/step - accuracy: 0.8200 - loss: 0.4243 - val_accuracy: 0.8372 - val_loss: 0.3868
Epoch 3/20
11621/11621 ━━━━━━━━━━━━━━━━━━━━ 71s 6ms/step - accuracy: 0.8440 - loss: 0.3721 - val_accuracy: 0.8517 - val_loss: 0.3525
Epoch 4/20
11621/11621 ━━━━━━━━━━━━━━━━━━━━ 75s 6ms/step - accuracy: 0.8586 - loss: 0.3397 - val_accuracy: 0.8646 - val_loss: 0.3295
Epoch 5/20
11621/11621 ━━━━━━━━━━━━━━━━━━━━ 40s 3ms/step - accuracy: 0.8675 - loss: 0.3193 - val_accuracy: 0.8726 - val_loss: 0.3133
Epoch 6/20
11621/11621 ━━━━━━━━━━━━━━━━━━━━ 46s 4ms/step - accuracy: 0.8741 - loss: 0.3076 - val_accuracy: 0.8697 - val_loss: 0.3124
Epoch 7/20
11621/11621 ━━━━━━━━━━━━━━━━━━━━ 46s 4ms/step - accuracy: 0.8804 - loss: 0.2937 - val_accuracy: 0.8784 - val_loss: 0.3037
Epoch 8/20
11621/11621 ━━━━━━━━━━━━━━━━━━━━ 52s 5ms/step - accuracy: 

C:\Users\Madhu Mohan Vamsi\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:2916: UserWarning: The y_pred values do not sum to one. Starting from 1.5 thiswill result in an error.
  warnings.warn(


AUC-ROC for Class 0: 0.983
AUC-ROC for Class 1: 0.980
AUC-ROC for Class 2: 0.997
AUC-ROC for Class 3: 0.998
AUC-ROC for Class 4: 0.994
AUC-ROC for Class 5: 0.996
AUC-ROC for Class 6: 0.999
Accuracy: 0.905
Precision: 0.867
Recall: 0.785
F1-Score: 0.813
AUC-ROC: 0.992
AUC-PR: 0.905
Log Loss: 0.233
Cohen's Kappa: 0.848
Confusion Matrix:
[[38239  4000     0     0    46     5   267]
 [ 3187 52617   187     0   385    77    47]
 [    3   199  6587    20    39   273     0]
 [    0     0   263   208     0    55     0]
 [   51   448    31     0  1461     4     0]
 [    6   338   647    15     1  2482     0]
 [  319    73     0     0     0     0  3623]]
Average Brier Score: 0.019
Matthews Correlation Coefficient: 0.848
Fowlkes-Mallows Index: 0.844
Coefficient of Determination (R^2): 0.748
Top-3 Accuracy: 0.999
